package com.riviem.sunalarm.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

val BackgroundBottomColor = Color(0xFF1F2236)

// Settings Switch
val SettingsActivateSwitchButtonColor = Color(0xFF91FFE8)
val SettingsInactiveSwitchButtonColor = Color(0xFF808080)
val SettingsInactiveSwitchTrackColor = Color(0xFFD3D3D3)
val SettingsInactiveSwitchBorderColor = Color(0xFF8C8C8C)
val SettingsInactiveSwitchIconColor = Color.White
val SettingsDisabledSwitchButtonColor = Color(0xFFE0E0E0)
val SettingsDisabledSwitchTrackColor = Color(0xFFCDCDCD)
val SettingsDisabledSwitchBorderColor = Color(0xFFA8A8A8)
val SettingsDisabledSwitchIconColor = Color.Gray

// Theme
val md_theme_light_primary = Color(0xFF795900)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDF9F)
val md_theme_light_onPrimaryContainer = Color(0xFF261A00)
val md_theme_light_secondary = Color(0xFF6B5C3F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5E0BB)
val md_theme_light_onSecondaryContainer = Color(0xFF241A04)
val md_theme_light_tertiary = Color(0xFF646100)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFEDE76D)
val md_theme_light_onTertiaryContainer = Color(0xFF1E1C00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B16)
val md_theme_light_surfaceVariant = Color(0xFFEDE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4D4639)
val md_theme_light_outline = Color(0xFF7F7667)
val md_theme_light_inverseOnSurface = Color(0xFFF8EFE7)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFF3BF48)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF795900)
val md_theme_light_outlineVariant = Color(0xFFD0C5B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFF3BF48)
val md_theme_dark_onPrimary = Color(0xFF402D00)
val md_theme_dark_primaryContainer = Color(0xFF5C4300)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDF9F)
val md_theme_dark_secondary = Color(0xFFD8C4A0)
val md_theme_dark_onSecondary = Color(0xFF3B2F15)
val md_theme_dark_secondaryContainer = Color(0xFF52452A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF5E0BB)
val md_theme_dark_tertiary = Color(0xFFD0CB54)
val md_theme_dark_onTertiary = Color(0xFF343200)
val md_theme_dark_tertiaryContainer = Color(0xFF4B4900)
val md_theme_dark_onTertiaryContainer = Color(0xFFEDE76D)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE9E1D8)
val md_theme_dark_surface = Color(0xFF1E1B16)
val md_theme_dark_onSurface = Color(0xFFE9E1D8)
val md_theme_dark_surfaceVariant = Color(0xFF4D4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C5B4)
val md_theme_dark_outline = Color(0xFF998F80)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE9E1D8)
val md_theme_dark_inversePrimary = Color(0xFF795900)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF3BF48)
val md_theme_dark_outlineVariant = Color(0xFF4D4639)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFAE5C0)
